// <auto-generated />
using System;
using GastroManagerBE.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GastroManagerBE.Migrations
{
    [DbContext(typeof(GastroManagerContext))]
    [Migration("20240815224255_CrearBD")]
    partial class CrearBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GastroManagerBE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Name = "Fritos"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Name = "Bebidas"
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BirthdayDate = new DateTime(2000, 6, 10, 5, 20, 48, 608, DateTimeKind.Local).AddTicks(4944),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Louis38@yahoo.com",
                            Name = "Louis Beatty",
                            NumberPhone = "(548) 543-4410 x35802"
                        },
                        new
                        {
                            CustomerId = 2,
                            BirthdayDate = new DateTime(1967, 8, 19, 13, 39, 37, 908, DateTimeKind.Local).AddTicks(8627),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Walter85@yahoo.com",
                            Name = "Walter Brown",
                            NumberPhone = "(588) 292-0948 x30782"
                        },
                        new
                        {
                            CustomerId = 3,
                            BirthdayDate = new DateTime(1990, 4, 10, 19, 49, 26, 780, DateTimeKind.Local).AddTicks(3373),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Carlos_Torp@yahoo.com",
                            Name = "Carlos Torp",
                            NumberPhone = "(242) 975-7187"
                        },
                        new
                        {
                            CustomerId = 4,
                            BirthdayDate = new DateTime(2000, 11, 8, 4, 27, 27, 98, DateTimeKind.Local).AddTicks(4925),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Malcolm.Koepp71@hotmail.com",
                            Name = "Malcolm Koepp",
                            NumberPhone = "574.210.7496"
                        },
                        new
                        {
                            CustomerId = 5,
                            BirthdayDate = new DateTime(1984, 4, 27, 1, 30, 0, 806, DateTimeKind.Local).AddTicks(6910),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Caleb.Hayes23@gmail.com",
                            Name = "Caleb Hayes",
                            NumberPhone = "(624) 639-2607 x8843"
                        },
                        new
                        {
                            CustomerId = 6,
                            BirthdayDate = new DateTime(1968, 10, 19, 7, 58, 58, 223, DateTimeKind.Local).AddTicks(7538),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Domingo24@gmail.com",
                            Name = "Domingo Schimmel",
                            NumberPhone = "409.485.5541 x55183"
                        },
                        new
                        {
                            CustomerId = 7,
                            BirthdayDate = new DateTime(1962, 12, 14, 2, 3, 37, 677, DateTimeKind.Local).AddTicks(610),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Allen.Kihn8@hotmail.com",
                            Name = "Allen Kihn",
                            NumberPhone = "1-422-282-8189 x0674"
                        },
                        new
                        {
                            CustomerId = 8,
                            BirthdayDate = new DateTime(1980, 3, 19, 22, 47, 24, 716, DateTimeKind.Local).AddTicks(3707),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Blake.Stamm@gmail.com",
                            Name = "Blake Stamm",
                            NumberPhone = "724-617-2415"
                        },
                        new
                        {
                            CustomerId = 9,
                            BirthdayDate = new DateTime(1999, 10, 10, 5, 30, 57, 240, DateTimeKind.Local).AddTicks(5908),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Daisy.Schultz@yahoo.com",
                            Name = "Daisy Schultz",
                            NumberPhone = "1-650-567-3969"
                        },
                        new
                        {
                            CustomerId = 10,
                            BirthdayDate = new DateTime(1985, 12, 24, 19, 52, 13, 199, DateTimeKind.Local).AddTicks(2378),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "Winifred_Kunde89@gmail.com",
                            Name = "Winifred Kunde",
                            NumberPhone = "781-592-7163"
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrderCustomerId")
                        .HasColumnType("int");

                    b.Property<float>("PriceProduct")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("OrderCustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 18,
                            PriceProduct = 40468f,
                            ProductId = 1
                        },
                        new
                        {
                            InvoiceId = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 8,
                            PriceProduct = 68857f,
                            ProductId = 3
                        },
                        new
                        {
                            InvoiceId = 3,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 37,
                            PriceProduct = 48650f,
                            ProductId = 1
                        },
                        new
                        {
                            InvoiceId = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 19,
                            PriceProduct = 76417f,
                            ProductId = 1
                        },
                        new
                        {
                            InvoiceId = 5,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 31,
                            PriceProduct = 56505f,
                            ProductId = 3
                        },
                        new
                        {
                            InvoiceId = 6,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 15,
                            PriceProduct = 83228f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 7,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 13,
                            PriceProduct = 74014f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 8,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 20,
                            PriceProduct = 19336f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 9,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 2,
                            PriceProduct = 28295f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 10,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 17,
                            PriceProduct = 64514f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 11,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 24,
                            PriceProduct = 47870f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 12,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 2,
                            PriceProduct = 17613f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 13,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 39,
                            PriceProduct = 40239f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 14,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 32,
                            PriceProduct = 43821f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 15,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 39,
                            PriceProduct = 71045f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 16,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 20,
                            PriceProduct = 19009f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 17,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 18,
                            PriceProduct = 83340f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 18,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 30,
                            PriceProduct = 60376f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 19,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 11,
                            PriceProduct = 39212f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 20,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 4,
                            PriceProduct = 38211f,
                            ProductId = 3
                        },
                        new
                        {
                            InvoiceId = 21,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 23,
                            PriceProduct = 26345f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 22,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 20,
                            PriceProduct = 69511f,
                            ProductId = 1
                        },
                        new
                        {
                            InvoiceId = 23,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 34,
                            PriceProduct = 52971f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 24,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 24,
                            PriceProduct = 31371f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 25,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 23,
                            PriceProduct = 26074f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 26,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 28,
                            PriceProduct = 31070f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 27,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 35,
                            PriceProduct = 66739f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 28,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 18,
                            PriceProduct = 86000f,
                            ProductId = 1
                        },
                        new
                        {
                            InvoiceId = 29,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 39,
                            PriceProduct = 38361f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 30,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 13,
                            PriceProduct = 63627f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 31,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 9,
                            PriceProduct = 60511f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 32,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 35,
                            PriceProduct = 47124f,
                            ProductId = 3
                        },
                        new
                        {
                            InvoiceId = 33,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 4,
                            PriceProduct = 84570f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 34,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 25,
                            PriceProduct = 38760f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 35,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 39,
                            PriceProduct = 67394f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 36,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 39,
                            PriceProduct = 55588f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 37,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 9,
                            PriceProduct = 92749f,
                            ProductId = 1
                        },
                        new
                        {
                            InvoiceId = 38,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 17,
                            PriceProduct = 80194f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 39,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 31,
                            PriceProduct = 51691f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 40,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 5,
                            PriceProduct = 88667f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 41,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 33,
                            PriceProduct = 78145f,
                            ProductId = 1
                        },
                        new
                        {
                            InvoiceId = 42,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 21,
                            PriceProduct = 68756f,
                            ProductId = 4
                        },
                        new
                        {
                            InvoiceId = 43,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 2,
                            PriceProduct = 78885f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 44,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 27,
                            PriceProduct = 83656f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 45,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 7,
                            PriceProduct = 64633f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 46,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 8,
                            PriceProduct = 89680f,
                            ProductId = 2
                        },
                        new
                        {
                            InvoiceId = 47,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 24,
                            PriceProduct = 62291f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 48,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 39,
                            PriceProduct = 93243f,
                            ProductId = 3
                        },
                        new
                        {
                            InvoiceId = 49,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 6,
                            PriceProduct = 15337f,
                            ProductId = 5
                        },
                        new
                        {
                            InvoiceId = 50,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            OrderCustomerId = 37,
                            PriceProduct = 16300f,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.OrderCustomer", b =>
                {
                    b.Property<int>("OrderCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TableRestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderCustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableRestaurantId");

                    b.ToTable("OrderCustomers");

                    b.HasData(
                        new
                        {
                            OrderCustomerId = 1,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 2,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 3,
                            OrderTime = new DateTime(2024, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 3,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 2,
                            OrderTime = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 4,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 2,
                            OrderTime = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 5,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 4,
                            OrderTime = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 6,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 1,
                            OrderTime = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 7,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 2,
                            OrderTime = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 8,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 7,
                            OrderTime = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 9,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 2,
                            OrderTime = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 10,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 3,
                            OrderTime = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 11,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 4,
                            OrderTime = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 12,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 7,
                            OrderTime = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 13,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 6,
                            OrderTime = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 14,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 6,
                            OrderTime = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 15,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 8,
                            OrderTime = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 16,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 4,
                            OrderTime = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 17,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 18,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 19,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 20,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 8,
                            OrderTime = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 21,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 5,
                            OrderTime = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 22,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 5,
                            OrderTime = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 23,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 1,
                            OrderTime = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 24,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 7,
                            OrderTime = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 25,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 2,
                            OrderTime = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 26,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 1,
                            OrderTime = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 27,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 8,
                            OrderTime = new DateTime(2024, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 28,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 3,
                            OrderTime = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 29,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 2,
                            OrderTime = new DateTime(2024, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 30,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 1,
                            OrderTime = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 31,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 32,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 4,
                            OrderTime = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        },
                        new
                        {
                            OrderCustomerId = 33,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 5,
                            OrderTime = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 34,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 4,
                            OrderTime = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 35,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 5,
                            OrderTime = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 36,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 2
                        },
                        new
                        {
                            OrderCustomerId = 37,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 8,
                            OrderTime = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 38,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 7,
                            OrderTime = new DateTime(2024, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 39,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 5,
                            OrderTime = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 1
                        },
                        new
                        {
                            OrderCustomerId = 40,
                            Amount = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            CustomerId = 4,
                            OrderTime = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableRestaurantId = 3
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Available = true,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Description = "Bebida con sabor a cola",
                            Image = "https://images.pexels.com/photos/4389680/pexels-photo-4389680.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Name = "Cocacola",
                            Price = 3500f
                        },
                        new
                        {
                            ProductId = 2,
                            Available = true,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Description = "Gaseosa Postobon",
                            Image = "https://mandalomarket.com/wp-content/uploads/2024/01/refresco1.jpg",
                            Name = "Manzana",
                            Price = 4000f
                        },
                        new
                        {
                            ProductId = 3,
                            Available = true,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Description = "Jugo de sabor Naranja",
                            Image = "https://vixark.b-cdn.net/lp-i-i-g/jugo-de-naranja-hit-1000ml.jpg",
                            Name = "Jugo Hit",
                            Price = 4500f
                        },
                        new
                        {
                            ProductId = 4,
                            Available = true,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Description = "Jugo Natural de Matacuya",
                            Image = "https://images.pexels.com/photos/4958875/pexels-photo-4958875.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Name = "Jugo Maracuya",
                            Price = 8000f
                        },
                        new
                        {
                            ProductId = 5,
                            Available = true,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Description = "Carne 150gr - Queso - vegetales",
                            Image = "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Name = "Hamburguesa Secilla",
                            Price = 15000f
                        },
                        new
                        {
                            ProductId = 6,
                            Available = true,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Description = "Salchicha Americana",
                            Image = "https://images.pexels.com/photos/4676419/pexels-photo-4676419.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Name = "Perro Caliente",
                            Price = 12000f
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("NameCustomer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumberGuest")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneCustomer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("GastroManagerBE.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "Ibague - Tolima",
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Name = "La casa Familiar"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "Cartagena - Bolivar",
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Name = "El sabor de la Calle"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "Cartagena - Bolivar",
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Name = "El sabor de la Calle"
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.TableRestaurant", b =>
                {
                    b.Property<int>("TableRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TableRestaurantId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("TableRestaurants");

                    b.HasData(
                        new
                        {
                            TableRestaurantId = 1,
                            Available = true,
                            Capacity = 6,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Number = "A-1",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableRestaurantId = 2,
                            Available = true,
                            Capacity = 4,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Number = "A-2",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableRestaurantId = 3,
                            Available = true,
                            Capacity = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Number = "A-3",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableRestaurantId = 4,
                            Available = true,
                            Capacity = 5,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Number = "A-4",
                            RestaurantId = 1
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "yule@gmail.com",
                            Password = "abcd",
                            Role = "Admin",
                            Username = "Yule"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 8, 15, 17, 42, 55, 336, DateTimeKind.Utc).AddTicks(6636),
                            CreatedBy = "Yuleiny",
                            Email = "user@gmail.com",
                            Password = "1234",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("GastroManagerBE.Models.Invoice", b =>
                {
                    b.HasOne("GastroManagerBE.Models.OrderCustomer", "OrderCustomer")
                        .WithMany()
                        .HasForeignKey("OrderCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastroManagerBE.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderCustomer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GastroManagerBE.Models.OrderCustomer", b =>
                {
                    b.HasOne("GastroManagerBE.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastroManagerBE.Models.TableRestaurant", "TableRestaurant")
                        .WithMany()
                        .HasForeignKey("TableRestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TableRestaurant");
                });

            modelBuilder.Entity("GastroManagerBE.Models.Product", b =>
                {
                    b.HasOne("GastroManagerBE.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GastroManagerBE.Models.Reservation", b =>
                {
                    b.HasOne("GastroManagerBE.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastroManagerBE.Models.TableRestaurant", "TableRestaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TableRestaurant");
                });

            modelBuilder.Entity("GastroManagerBE.Models.TableRestaurant", b =>
                {
                    b.HasOne("GastroManagerBE.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
